let action = null;
let type = "orden";
let appliedDiscount = 0;
let cuponUsado = false;
var totalActual = 0;

async function startOfPage() {
  checkValidarButtonState();
  GetDataAndPopulateSelectCli()
  cargarvalidacioncupones();
  agregarProducto(true);  
  
  //await GetDataAndPopulateTable();
  let urlId = getIdFromURL();
  if (urlId) GetDataOfSpecificId(urlId);

  var btnDeleteOrden = document.querySelectorAll(".btnDeleteOrden");
  console.log(btnDeleteOrden);

  const btnCreateOrden = document.getElementById("btnCreateCliente"); // Assuming this is the correct button ID
  if (btnCreateOrden) {
  btnCreateOrden.addEventListener("click", function (e) {
    e.preventDefault();
    validarNuevaOrden();
  });
}

  if (btnDeleteOrden != null) {
    for (var i = 0; i < btnDeleteOrden.length; i++) {
      btnDeleteOrden[i].addEventListener("click", function (e) {
        e.preventDefault();
        var ordenId = this.getAttribute("orden-id");
        eliminarOrden(ordenId);
      });
    }
  }
}

function checkValidarButtonState() {
  var totalInput = document.getElementById("total");
  var btnValidar = document.getElementById("btnValitadeCupon");
  var isTotalValid = !isNaN(parseFloat(totalInput.value)) && parseFloat(totalInput.value) > 0;

  btnValidar.disabled = cuponUsado || !isTotalValid;  // Disable if coupon used or total invalid
  console.log('isTotalValid:', isTotalValid);
  console.log('cuponUsado:', cuponUsado);
}

function cargarvalidacioncupones() {
  document.getElementById('btnValitadeCupon').addEventListener('click', async function(e) {
    e.preventDefault();
    var cuponCodigo = document.getElementById('codigo-cupon').value;
    var iconSpan = document.querySelector('.input-group-text i');

    try {
      var descuento = await validarCupon(cuponCodigo);
      Swal.fire({
        icon: 'success',
        title: '¡Cupón válido!',
        text: `Se aplicó un descuento de ${descuento}%`,
      });
      // Cambiar clase del icono a check si el cupón es válido
      iconSpan.className = 'bi bi-check-circle-fill text-success';
    } catch (error) {
      console.error('Error al validar el cupón:', error);
      Swal.fire({
        icon: 'error',
        title: '¡Oops...',
        text: '¡Cupón inválido!',
      });
      // Cambiar clase del icono a x-circle si el cupón no es válido
      iconSpan.className = 'bi bi-x-circle-fill text-danger';
    }
  });
}






function goToList() {
  window.open("ordenList.html", "_self");
}

function callINFUsuario(id) {
  return new Promise((resolve, reject) => {
    var apiURL = `http://localhost:4090/api/Cliente/obtenerClientePorId/${id}`;
    $.ajax({
      method: "GET",
      url: apiURL,
      success: function (response) {
        resolve(response.nombreCompleto);
      },
      error: function (error) {
        reject(error);
      },
    });
  });
}

function callINFProducto(id) {
  return new Promise((resolve, reject) => {
    var apiURL = `http://localhost:4090/api/Producto/obtenerProductoPorId/${id}`;
    $.ajax({
      method: "GET",
      url: apiURL,
      success: function (response) {
        resolve(response.nombre);
      },
      error: function (error) {
        reject(error);
      },
    });
  });
}

function validarNuevaOrden() {
  const clienteId = document.getElementById('clientesSelect').value;
  const codigoCupon = document.getElementById('codigo-cupon').value;
  const total = document.getElementById('total').value;

  // Validate required fields and details
  if (!clienteId || detalles.length === 0 || !total) {
    Swal.fire({
      title: "Error",
      icon: "error",
      text: "Please select a client, add at least one product, and ensure the total is calculated.",
    });
    return;
  }

  const tempIDs = [];

  // Create order details first
  for (const detalle of detalles) {
    $.ajax({
      headers: {
        Accept: "application/json",
      },
      method: "POST",
      url: "http://localhost:4090/api/DetalleOrden/crear", // Endpoint for creating details
      dataType: "json",
      data: JSON.stringify(detalle),
      success: function(response) {
        tempIDs.push(response.detalleId);

        // If all details created, create the order
        if (tempIDs.length === detalles.length) {
          crearOrden(clienteId, codigoCupon, tempIDs, total);
        }
      },
      error: function(xhr, status, error) {
        console.error("Error creating order details:", error);
        Swal.fire({
          icon: "error",
          title: "Oops...",
          text: "Error creating order details!",
        });
      },
    });
  }
}

function crearOrden(clienteId, codigoCupon, detallesIDs, total) {
  const nuevaOrden = { 
    // ordenId: will be generated by backend,
    clienteId, 
    cuponId: codigoCupon ? codigoCupon : null, // Assuming null for no coupon
    fecha: new Date().toISOString(),
    total,
    detalles: detallesIDs 
  };

  $.ajax({
    headers: {
      Accept: "application/json",
    },
    method: "POST",
    url: "http://localhost:4090/api/Orden/crear", // Endpoint for creating orders
    dataType: "json",
    data: JSON.stringify(nuevaOrden),
    hasContent: true,
    statusCode: {
      200: function () {
        mostrarMensaje("creada", 200), clearFormFields(), waitForConfirmation();
      }
      // ... other status codes
    },
  });
}




async function GetDataAndPopulateTable() {
  return new Promise((resolve, reject) => {
    var apiUrl = "http://localhost:4090/api/Orden/obtenerTodasLasOrdenes";

    $.ajax({
      url: apiUrl,
      method: "GET",
      dataType: "json",
    })
      .done(async function (data) {
        // *** Check if data is valid before proceeding ***
        if (!data || data.length === 0 || typeof data[0].usuarioId === 'undefined') {
          console.error("Invalid data received from API."); 
          // Handle the error (e.g., display a message to the user)
          return; // Or throw an error to stop execution
        }

        var tableBody = $("#dynamicTableBody");
        tableBody.empty();

        var requests = [];

        for (var i = 0; i < data.length; i++) {
          var usuarioRequest = callINFUsuario(data[i].usuarioId);
          requests.push(usuarioRequest);
        }

        var responses = await Promise.all(requests);

        for (var i = 0; i < responses.length; i++) {
          var usuarioName = responses[i];

          tableBody.append(
            "<tr>" +
            '<th scope="row" class="txtId">' +
            data[i].ordenId +
            "</th>" +
            '<td class="txtUsuarioId">' +
            usuarioName +
            "</td>" +
            '<td class="codigoCupon">' +
            data[i].codigoCupon +
            "</td>" +
            '<td class="actionDelete"><a class="btnDecoratioStyleMod btnModifyOrden" href="ordenModify.html?id=' +
            data[i].ordenId +
            '">Actualizar</a> / <a  href="#" class="btnDecoratioStyleDel btnDeleteOrden" orden-id="' +
            data[i].ordenId +
            '">Eliminar</a></td>' +
            "</tr>"
          );
        }

        resolve();
      })
      .fail(function (error) {
        Swal.fire({
          icon: "error",
          title: "Oops...",
          text: "Error!",
        });
        reject();
      });
  });
}

function eliminarOrden(id) {
  var apiUrl = `http://localhost:4090/api/Orden/eliminarOrden/${id}`;
  $.ajax({
    headers: {
      Accept: "application/json",
    },
    method: "DELETE",
    url: apiUrl,
    dataType: "json",
    statusCode: {
      200: function () {
        mostrarMensaje("eliminada", 200), startOfPage();
      },
      201: function () {
        mostrarMensaje("eliminada", 201), startOfPage();
      },
      400: function () {
        mostrarMensaje("eliminar", 400);
      },
      404: function () {
        mostrarMensaje("eliminar", 404);
      },
      500: function () {
        mostrarMensaje("eliminar", 500);
      },
    },
  });
}

function getIdFromURL() {
  var urlParams = new URLSearchParams(window.location.search);
  return urlParams.get("id");
}

async function GetDataOfSpecificId(selectedOrdenId) {
  var apiUrl = `http://localhost:4090/api/Orden/obtenerOrdenPorId/${selectedOrdenId}`;
  try {
    var response = await $.ajax({
      method: "GET",
      url: apiUrl,
    });
    var usuarioName = await callINFUsuario(response.usuarioId);

    var clientesSelect = $("#clientesSelect");

    var clienteOption = clientesSelect.find(`option[value="${response.usuarioId}"]`);
    if (clienteOption.length) {
      clienteOption.text(usuarioName);
    } else {
      clientesSelect.append(`<option value="${response.usuarioId}">${usuarioName}</option>`);
    }

    clientesSelect.val(response.usuarioId);

    $("#clientePRA").val(response.codigoCupon);
  } catch (error) {
    console.error(error);
  }
}

function modificarOrden() {
  var id = getIdFromURL();
  var cliente = document.getElementById('clientesSelect').value;
  var cupon = document.getElementById('clientePRA').value;
  if (cliente.trim() !== '' && cupon.trim() !== '') {
    var actualizarOrden = {
      ordenId: id,
      clienteId: cliente,
      codigoCupon: cupon
    };
    var apiUrl = "http://localhost:4090/api/Orden/actualizarOrden";

    $.ajax({
      headers: {
        Accept: "application/json",
      },
      method: "PUT",
      url: apiUrl,
      dataType: "json",
      data: JSON.stringify(actualizarOrden),
      hasContent: true,
      statusCode: {
        200: function () {
          mostrarMensaje("actualizada", 200),
            clearFormFields(),
            waitForConfirmation();
        },
        201: function () {
          mostrarMensaje("actualizada", 201),
            clearFormFields(),
            waitForConfirmation();
        },
        400: function () {
          mostrarMensaje("actualizar", 400);
        },
        404: function () {
          mostrarMensaje("actualizar", 404);
        },
        500: function () {
          mostrarMensaje("actualizar", 500);
        },
      },
    });
  } else {
    Swal.fire({
      title: "Message",
      icon: "error",
      text: "Por favor, complete todos los campos.",
    });
  }
}

function GetDataAndPopulateSelectCli() {
  var apiUrl = "http://localhost:4090/api/Cliente/obtenerClientes"; 

  $.ajax({
    url: apiUrl,
    method: "GET",
    dataType: "json",
  })
    .done(function (data) {
      var selectOptions = $("#clientesSelect");
      selectOptions.empty();

      // Add a disabled placeholder option
      selectOptions.append('<option value="" disabled selected>Selecciona un cliente</option>'); 

      for (var i = 0; i < data.length; i++) {
        selectOptions.append(
          '<option value="' + data[i].clienteId + '">' + 
          data[i].nombre + ' ' + data[i].primerApellido + ' ' + data[i].segundoApellido + 
          '</option>' 
        );
      }
    })
    .fail(function (error) {
      Swal.fire({
        icon: "error",
        title: "Oops...",
        text: "Error al cargar clientes!", 
      });
    });
}

function agregarProducto(isFirst) {
  var productosContainer = $("#productosContainer");
  var productoRow = $("<div></div>").addClass("form-group producto-row");
  productoRow.html(`
    ${isFirst ? '' : '<hr class="EL--hr-gradient">'}
    <div class="row align-items-center">
      <div class="col-12 mb-4">
        <label for="productos" class="mb-0">Producto:</label>                     
        <select name="productos[]" class="form-control productosSelect" required></select>
      </div>
      <div class="col-6 text-center">
        <label for="cantidad" class="mb-0">Cantidad:</label>
        <div class="input-group">
          <span class="input-group-btn">
            <button class="btn btn-outline-secondary decreaseBtn" type="button">-</button>
          </span>
          <input type="text" name="quant[]" class="form-control quantity-input" value="1" min="1" max="99"> 
          <span class="input-group-btn">
            <button class="btn btn-outline-secondary increaseBtn" type="button">+</button>
          </span>
        </div>
      </div>
      <div class="col-6">
        <label for="precio" class="mb-0">Precio:</label>
        <input type="text" class="form-control price-input" name="precio[]" required disabled>                   
      </div>     
      ${isFirst ? '' : '<div class="col-6 d-flex justify-content-center align-items-stretch flex-column text-right pt-3"><button type="button" class="btn btn-danger btn-sm btn-remove-producto" onclick="eliminarProducto(this)"><span class="bi bi-trash"></span> Eliminar</button></div>'}
    </div>
  `);

  // Agregar event listeners a los botones de incremento y decremento
  productoRow.find(".decreaseBtn").click(function() {
    decrementarCantidad(this);
  });
  productoRow.find(".increaseBtn").click(function() {
    incrementarCantidad(this);
  });
  productoRow.find(".productosSelect").change(function() {
    updatePriceAndTotal(this, $(this).closest('.producto-row').find('.quantity-input'), $(this).closest('.producto-row').find('.price-input'));
  });

  // Obtener los productos seleccionados en las filas anteriores
  var selectedProducts = [];
  productosContainer.find('.productosSelect').each(function() {
    var selectedProduct = $(this).val();
    if (selectedProduct !== 'null') {
      selectedProducts.push(selectedProduct);
    }
  });

  productosContainer.append(productoRow);

  // Llenar el select de productos excluyendo los productos seleccionados previamente
  fillProductSelect(productoRow.find(".productosSelect"), selectedProducts);

}

function fillProductSelect(selectElement, excludedProducts) {
  var apiUrl = "http://localhost:4090/api/Producto/obtenerProductos";

  $.ajax({
    url: apiUrl,
    method: "GET",
    dataType: "json",
    success: function (data) {
      selectElement.empty();
      selectElement.append('<option value="null" disabled>--Selecciona--</option>');

      $.each(data, function (index, producto) {
        if (!excludedProducts.includes(producto.productoId)) {
          selectElement.append(
            '<option value="' + producto.productoId + '" data-price="' + producto.precio + '">' + producto.nombre + '</option>'
          );
        }
      });
      selectElement.val("null");
    },
    error: function (error) {
      console.error("Error al obtener productos:", error);
      Swal.fire({
        icon: "error",
        title: "Oops...",
        text: "Error al cargar productos!",
      });
    },
  });
}

function updatePriceAndTotal(productSelect, quantityInput, precioInput) {
  var selectedOption = productSelect.options[productSelect.selectedIndex];
  var productPrice = parseFloat(selectedOption.dataset.price || 0);
  var quantity = parseFloat(quantityInput.val() || 0);
  var rowPrice = productPrice * quantity;
  precioInput.val(rowPrice.toFixed(2));

  recalcularTotal();
}

async function validarCupon(cuponCodigo) {
  return new Promise((resolve, reject) => {
    var apiUrl = `http://localhost:4090/api/Cupon/obtenerCuponPorId/${cuponCodigo}`;

    $.ajax({
      url: apiUrl,
      method: "GET",
      dataType: "json",
    })
    .done(function (response) {
      if (response.descuento !== null) {
        var descuento = response.descuento;
        appliedDiscount = descuento;
        recalcularTotal();
        cuponUsado = true; 
        checkValidarButtonState();

          Swal.fire({
            icon: 'success',
            title: '¡Cupón válido!',
            text: `Se aplicó un descuento de ${descuento}%`,
          });
        } else {
          Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: 'Cupón inválido o sin descuento!',
          });
          reject(new Error("Invalid coupon or no discount"));
        }
      })
      .fail(function (error) {
        console.error("Error validating coupon:", error);
        reject(error);
      });
  });
}

function incrementarCantidad(button) {
  var input = button.parentNode.parentNode.querySelector(".quantity-input");
  var currentValue = parseInt(input.value);
  if (!isNaN(currentValue) && currentValue < 99) {
    input.value = currentValue + 1;
    updatePriceAndTotal(input.closest(".producto-row").querySelector(".productosSelect"), input, input.closest(".producto-row").querySelector(".price-input"));
  }
}

function decrementarCantidad(button) {
  var input = button.parentNode.parentNode.querySelector(".quantity-input");
  var currentValue = parseInt(input.value);
  if (!isNaN(currentValue) && currentValue > 1) {
    input.value = currentValue - 1;
    updatePriceAndTotal(input.closest(".producto-row").querySelector(".productosSelect"), input, input.closest(".producto-row").querySelector(".price-input"));
  }
}

function recalcularTotal() {
  var productRows = document.querySelectorAll(".producto-row");
  var total = 0;
  productRows.forEach(function(row) {
    var rowPriceInput = row.querySelector(".price-input");
    var rowPrice = parseFloat(rowPriceInput.value || 0);
    if (!isNaN(rowPrice)) {
      total += rowPrice;
    }
  });

  if (appliedDiscount > 0) {
    var descuentoCantidad = total * (appliedDiscount / 100);
    total -= descuentoCantidad;
  }

  document.getElementById("total").value = total.toFixed(2);
  checkValidarButtonState();
}

function eliminarProducto(button) {
  var row = button.closest('.producto-row');
  var priceInput = row.querySelector('.price-input');
  var price = parseFloat(priceInput.value) || 0;

  // Restar el precio del producto eliminado del total
  var totalInput = document.getElementById("total");
  var currentTotal = parseFloat(totalInput.value) || 0;
  var newTotal = Math.max(0, currentTotal - price); // No permitir que el total sea negativo
  totalInput.value = newTotal.toFixed(2);

  // Eliminar la fila del producto
  row.remove();
  recalcularTotal();
}

window.onload = function () {
  startOfPage();
};

function waitForConfirmation() {
  document.addEventListener("click", function (event) {
    var target = event.target;
    if (
      target &&
      target.classList.contains("swal2-confirm") &&
      target.classList.contains("swal2-styled")
    ) {
      goToList();
    }
  });
}

function clearFormFields() {
  var inputFields = document.querySelectorAll("input, textarea, select");
  inputFields.forEach(function (field) {
    field.value = "";
  });
}

function goBack() {
  window.history.back();
}